### ISSUE TITLE
checkerboard logmar start 

### ISSUE THREAD

**Issue by KRolnick89** [tbenst/glia#9]
In my last few runs, it appears the checkerboard logmar start being plotted in acuity isn't accurate to the eyecandy parameters that I set. 

10/25/17 R1_E1 lab notebook has:
nsizes = 6\r\nlet startLogMAR = 2.1\r\nlet logMarStep = 0.2

Classification acuity:
![checkerboard-contrast_acuity](https://user-images.githubusercontent.com/30326402/32111291-f0a24fda-baee-11e7-92da-c06cb1af36a5.png)

**Comment by tbenst** [comment]
Good catch! Glia is correct, those eyecandy protocols used an old measurement of 7.5px / degree. Fixed in latest eyecandy.

**Comment by KRolnick89** [comment]
Thank you, Tyler!
